---
title: "Untitled"
author: "Miles D. Williams"
date: "January 22, 2020"
output: html_document
---

# Open libraries

```{r}
try(library(tidyverse))
library(RFA)
```

# Get data

```{r}
dt = haven::read_dta("cwdata.dta")
ggplot(data = dt) +
  geom_density(aes(lagaidgdpchange)) +
  geom_vline(xintercept = c(quantile(dt$lagaidgdpchange, .25, na.rm=T),
                                quantile(dt$lagaidgdpchange, .75, na.rm=T))) +
  xlim(c(-.2,.2))
```

# Clean the data

```{r}
clean_dt = dt %>%
  transmute(
    # the response variable: civil war coded 1 if >= 25 battle deaths in a year (PRIO)
    civil_war = prio,
    
    # the causal variable of interest: aid_shock = neg. change in aid/gdp less than 15th percentile
    #aid_shock = as.numeric(lagaidgdpchange <= quantile(lagaidgdpchange, .8, na.rm=T)),
    #aid_shock = lagaidgdpchange <= -.0054,
    #aid_shock = lagaidgdpchange,
    #aid_shock = as.numeric(gtools::quantcut(lagaidgdpchange, q = c(.15,.5,.85))),
    neg_shock = as.numeric(lagaidgdpchange <= quantile(lagaidgdpchange, .25, na.rm=T)),
    nul_shock = as.numeric(lagaidgdpchange > quantile(lagaidgdpchange, .25, na.rm=T) &
                             lagaidgdpchange < quantile(lagaidgdpchange, .75, na.rm=T)),
    pos_shock = as.numeric(lagaidgdpchange >= quantile(lagaidgdpchange, .75, na.rm=T)),
    
    # counfounding variables
    x1 = PTSave_filled, # HR violations
    x2 = assassinbanks, # no. of assassinations
    x3 = riotsbanks, # no. of riots
    x4 = strikesbanks, # no. of strikes
    x5 = demonstrationsbanks, # no. of demonstrations
    x6 = infantmort, # infrant mortaility
    x7 = nciv, # no. of contiguous neighbors experiencing civil war
    x8 = partautocracy, # partial autocracy
    x9 = partdemocracy, # partial democracy
    x10 = factionaldemoc, # factional democracy
    x11 = fulldemocracy, # full democracy
    x12 = ln_rgdpc, # log of gdp/captita
    x13 = ln_population, # log of population
    x14 = oil, # oil exportation
    x15 = instab, # political instability
    x16 = ethfrac, # ethnic fractionalization
    x17 = relfrac, # religious fractionalization
    x18 = as.numeric(year <= 1991), # cold war
    x19 = logmtn, # mountains
    x20 = ncontig, # noncontiguous
    x21 = year,
    x22 = countryname
  ) %>% na.omit 
```

# Implement RFA

```{r}
rfa_neg = rfa(civil_war ~ neg_shock + 
                x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 +
                x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + 
                x20, 
              clean_dt)
rfa_nul = rfa(civil_war ~ nul_shock + 
                x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 +
                x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + 
                x20, 
              clean_dt)
rfa_pos = rfa(civil_war ~ pos_shock + 
                x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 +
                x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + 
                x20, 
              clean_dt)
```

```{r}
tibble(
  ate = c(rfa_neg$ate, rfa_nul$ate, rfa_pos$ate)*100,
  ses = c(sd(rfa_neg$bootate), sd(rfa_nul$bootate), sd(rfa_pos$bootate))*100,
  estimate = 1:3
) %>%
  ggplot() +
  aes(
    x = estimate,
    y = ate,
    ymin = ate - 1.96*ses,
    ymax = ate + 1.96*ses
  ) +
  geom_point() + 
  geom_errorbar(width = 0.25) +
  geom_hline(yintercept = 0) +
  labs(
    x = "Treatment",
    y = "Change in % Chance of Conflict",
    title = "The Causal Effect of Aid Shocks on Violent Conflict",
    subtitle = "Estimates generated via RFA"
  ) +
  scale_x_discrete(breaks = NULL) +
  annotate("text", x = 1:3, y = -4.5, label = c("Negative Shock","No Shock","Positive Shock")) +
  theme_test()
```

# Try with different cutoffs

```{r}
clean_dt2 = dt %>%
  transmute(
    # the response variable: civil war coded 1 if >= 25 battle deaths in a year (PRIO)
    civil_war = prio,
    
    # the causal variable of interest: aid_shock = neg. change in aid/gdp (will try at different cutoffs)
    aid_shock = lagaidgdpchange,
    
    # counfounding variables
    x1 = PTSave_filled, # HR violations
    x2 = log(lassassinbanks+1), # no. of assassinations
    x3 = log(lriotsbanks+1), # no. of riots
    x4 = log(lstrikesbanks+1), # no. of strikes
    x5 = log(ldemonstrationsbanks+1), # no. of demonstrations
    x6 = log(linfantmort+1), # infant mortaility
    x7 = lnciv, # no. of contiguous neighbors experiencing civil war
    x8 = lpartautocracy, # partial autocracy
    x9 = lpartdemocracy, # partial democracy
    x10 = lfactionaldemoc, # factional democracy
    x11 = lfulldemocracy, # full democracy
    x12 = lln_rgdpc, # log of gdp/captita
    x13 = lln_population, # log of population
    x14 = log(loil+1), # oil exportation
    x15 = linstab, # political instability
    x16 = ethfrac, # ethnic fractionalization
    x17 = relfrac, # religious fractionalization
    x18 = as.numeric(year <= 1991), # cold war
    x19 = logmtn, # mountains
    x20 = ncontig, # noncontiguous
    x21 = year,
    x22 = countryname
  ) %>% na.omit 
```

```{r}
qts = seq(.075, .925, by = .05)
ates = 0
ses = 0
for(i in 1:length(qts)){
  if(qts[i]<.5)  new_dt = clean_dt2 %>% mutate(aid_shock = aid_shock <= quantile(aid_shock, qts[i]))
  if(qts[i]>.5)  new_dt = clean_dt2 %>% mutate(aid_shock = aid_shock >= quantile(aid_shock, qts[i]))
  rfa_out_i = rfa(civil_war ~ aid_shock + 
                x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 +
                x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + 
                x20 + x21, 
              new_dt)
  ates[i] = rfa_out_i$ate
  ses[i] = sd(rfa_out_i$bootate)
  print(paste0(round(i/length(qts),2)*100,"% completed"), quote = F)
}
```

```{r}
change = round(100*quantile(clean_dt2$aid_shock,seq(0.075,0.925,by=0.05)) /
                 mean(dt$lagaidpergdp,na.rm=T), 2) 
tibble(
  qts = qts*100,
  ate = ates,
  lo = ate - 1.96*ses,
  hi = ate + 1.96*ses
) %>%
  ggplot() +
  aes(
    x = qts,
    y = ate,
    ymin = lo,
    ymax = hi
  ) + 
  geom_line() + 
  geom_ribbon(alpha = 0.5) +
  geom_hline(yintercept = c(0,-.09), color = c("black","grey"),
             size = c(.5,35)) +
  labs(
    x = "Percentile Cutoff for Aid Shocks",
    y = expression(Delta*" % Chance of Violent Conflict"),
    title = "The Effect of Aid Shocks on Violent Conflict",
    subtitle = "Estimates generated via RFA"
  ) +
  scale_x_continuous(breaks = qts*100) +
  scale_y_continuous(breaks = seq(-.06,0.05,by=0.01),
                     labels = seq(-.06,0.05,by=0.01)*100) +
  geom_vline(xintercept = 50, linetype = 2) +
  annotate(x = 43, y = -.03, "text", 
           label = "''%<-%'(-) shock'", parse = T) +
  annotate(x = 57, y = .03, "text", 
           label = "'(+) shock'%->%''", parse = T) +
  annotate(x = qts*100, y = -0.085, "text",
           label = change, angle = 45) +
  annotate(x = 15, y = -0.0725, "text",
           label = "'%'*Delta*'(aid per GDP)'", parse = T) +
  theme_test() +
  ggsave(
    "effect_of_shocks.pdf",
    units = "in",
    height = 4,
    width = 7
  )
```

